inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  Include:
    - Rakefile
    - lib/ber/**/*.rb
  Exclude:
    - '**/.*'
    - doc/**/*
    - spec/**/*
  TargetRubyVersion: 2.4
