inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  Include:
    - Rakefile
    - lib/ber/**/*.rb
  Exclude:
    - '**/.*'
    - doc/**/*
    - spec/**/*
  TargetRubyVersion: 2.4


Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
